import { Matchoff } from "./matchoff";

export const matchsoff: any[] = [
  // Ligue 1 (ID: 1)
  {
    id: 'm1',
    color: 'primary',
    title: 'Paris Saint-Germain vs Olympique de Marseille',
    datef: new Date('2024-08-10'),
    league: '1',
    homeTeam: 'Paris Saint-Germain',
    awayTeam: 'Olympique de Marseille',
    homeTeamLogo: 'https://crests.football-data.org/524.svg',
    awayTeamLogo: 'https://crests.football-data.org/523.svg',
    date: '2024-08-10T20:45:00Z',
    status: 'finished',
    isFinished: true,
    homeScore: 3,
    awayScore: 1,
  },
  {
    id: 'm2',
    color: 'primary',
    title: 'AS Monaco vs Lyon',
    datef: new Date('2024-08-14'),
    league: '1',
    homeTeam: 'AS Monaco',
    awayTeam: 'Lyon',
    homeTeamLogo: 'https://crests.football-data.org/521.svg',
    awayTeamLogo: 'https://crests.football-data.org/518.svg',
    date: '2024-08-14T19:00:00Z',
    status: 'scheduled',
    isFinished: false,
  },
  {
    id: 'm3',
    color: 'primary',
    title: 'Lille vs Rennes',
    datef: new Date('2024-08-17'),
    league: '1',
    homeTeam: 'Lille',
    awayTeam: 'Rennes',
    homeTeamLogo: 'https://crests.football-data.org/522.svg',
    awayTeamLogo: 'https://crests.football-data.org/526.svg',
    date: '2024-08-17T17:00:00Z',
    status: 'live',
    isFinished: false,
    homeScore: 1,
    awayScore: 2,
  },
  {
    id: 'm4',
    color: 'primary',
    title: 'Nice vs Nantes',
    datef: new Date('2024-08-18'),
    league: '1',
    homeTeam: 'Nice',
    awayTeam: 'Nantes',
    homeTeamLogo: 'https://crests.football-data.org/529.svg',
    awayTeamLogo: 'https://crests.football-data.org/532.svg',
    date: '2024-08-18T15:00:00Z',
    status: 'scheduled',
    isFinished: false,
  },

  // LaLiga (ID: 2)
  {
    id: 'm5',
    color: 'error',
    title: 'Real Madrid vs FC Barcelona',
    datef: new Date('2024-08-13'),
    league: '2',
    homeTeam: 'Real Madrid',
    awayTeam: 'FC Barcelona',
    homeTeamLogo: 'https://crests.football-data.org/86.svg',
    awayTeamLogo: 'https://crests.football-data.org/81.svg',
    date: '2024-08-13T21:00:00Z',
    status: 'scheduled',
    isFinished: false,
  },
  {
    id: 'm6',
    color: 'error',
    title: 'Atletico Madrid vs Sevilla',
    datef: new Date('2024-08-15'),
    league: '2',
    homeTeam: 'Atletico Madrid',
    awayTeam: 'Sevilla',
    homeTeamLogo: 'https://crests.football-data.org/78.svg',
    awayTeamLogo: 'https://crests.football-data.org/559.svg',
    date: '2024-08-15T20:00:00Z',
    status: 'live',
    isFinished: false,
    homeScore: 0,
    awayScore: 0,
  },
  {
    id: 'm7',
    color: 'error',
    title: 'Valencia vs Villarreal',
    datef: new Date('2024-08-16'),
    league: '2',
    homeTeam: 'Valencia',
    awayTeam: 'Villarreal',
    homeTeamLogo: 'https://crests.football-data.org/95.svg',
    awayTeamLogo: 'https://crests.football-data.org/94.svg',
    date: '2024-08-16T22:00:00Z',
    status: 'finished',
    isFinished: true,
    homeScore: 2,
    awayScore: 2,
  },
  {
    id: 'm8',
    color: 'error',
    title: 'Real Sociedad vs Betis',
    datef: new Date('2024-08-19'),
    league: '2',
    homeTeam: 'Real Sociedad',
    awayTeam: 'Real Betis',
    homeTeamLogo: 'https://crests.football-data.org/92.svg',
    awayTeamLogo: 'https://crests.football-data.org/90.svg',
    date: '2024-08-19T18:30:00Z',
    status: 'scheduled',
    isFinished: false,
  },

  // Premier League (ID: 3)
  {
    id: 'm9',
    color: 'warning',
    title: 'Manchester City vs Arsenal',
    datef: new Date('2024-08-11'),
    league: '3',
    homeTeam: 'Manchester City',
    awayTeam: 'Arsenal',
    homeTeamLogo: 'https://crests.football-data.org/65.svg',
    awayTeamLogo: 'https://crests.football-data.org/57.svg',
    date: '2024-08-11T18:30:00Z',
    status: 'scheduled',
    isFinished: false,
  },
  {
    id: 'm10',
    color: 'warning',
    title: 'Chelsea vs Tottenham',
    datef: new Date('2024-08-12'),
    league: '3',
    homeTeam: 'Chelsea',
    awayTeam: 'Tottenham',
    homeTeamLogo: 'https://crests.football-data.org/61.svg',
    awayTeamLogo: 'https://crests.football-data.org/73.svg',
    date: '2024-08-12T20:30:00Z',
    status: 'live',
    isFinished: false,
    homeScore: 1,
    awayScore: 1,
  },
  {
    id: 'm11',
    color: 'warning',
    title: 'Liverpool vs Manchester United',
    datef: new Date('2024-08-20'),
    league: '3',
    homeTeam: 'Liverpool',
    awayTeam: 'Manchester United',
    homeTeamLogo: 'https://crests.football-data.org/64.svg',
    awayTeamLogo: 'https://crests.football-data.org/66.svg',
    date: '2024-08-20T19:45:00Z',
    status: 'finished',
    isFinished: true,
    homeScore: 2,
    awayScore: 3,
  },
  {
    id: 'm12',
    color: 'warning',
    title: 'Aston Villa vs West Ham',
    datef: new Date('2024-08-21'),
    league: '3',
    homeTeam: 'Aston Villa',
    awayTeam: 'West Ham',
    homeTeamLogo: 'https://crests.football-data.org/58.svg',
    awayTeamLogo: 'https://crests.football-data.org/563.svg',
    date: '2024-08-21T17:00:00Z',
    status: 'scheduled',
    isFinished: false,
  },

  // Serie A (ID: 4)
  {
    id: 'm13',
    color: 'success',
    title: 'Juventus vs AC Milan',
    datef: new Date('2024-08-12'),
    league: '4',
    homeTeam: 'Juventus',
    awayTeam: 'AC Milan',
    homeTeamLogo: 'https://crests.football-data.org/109.svg',
    awayTeamLogo: 'https://crests.football-data.org/98.svg',
    date: '2024-08-12T21:00:00Z',
    status: 'live',
    isFinished: false,
    homeScore: 1,
    awayScore: 2,
  },
  {
    id: 'm14',
    color: 'success',
    title: 'Inter Milan vs Napoli',
    datef: new Date('2024-08-13'),
    league: '4',
    homeTeam: 'Inter Milan',
    awayTeam: 'Napoli',
    homeTeamLogo: 'https://crests.football-data.org/108.svg',
    awayTeamLogo: 'https://crests.football-data.org/113.svg',
    date: '2024-08-13T21:00:00Z',
    status: 'scheduled',
    isFinished: false,
  },
  {
    id: 'm15',
    color: 'success',
    title: 'AS Roma vs Lazio',
    datef: new Date('2024-08-14'),
    league: '4',
    homeTeam: 'AS Roma',
    awayTeam: 'Lazio',
    homeTeamLogo: 'https://crests.football-data.org/100.svg',
    awayTeamLogo: 'https://crests.football-data.org/110.svg',
    date: '2024-08-14T18:30:00Z',
    status: 'finished',
    isFinished: true,
    homeScore: 1,
    awayScore: 1,
  },
  {
    id: 'm16',
    color: 'success',
    title: 'Fiorentina vs Bologna',
    datef: new Date('2024-08-15'),
    league: '4',
    homeTeam: 'Fiorentina',
    awayTeam: 'Bologna',
    homeTeamLogo: 'https://crests.football-data.org/99.svg',
    awayTeamLogo: 'https://crests.football-data.org/102.svg',
    date: '2024-08-15T17:00:00Z',
    status: 'scheduled',
    isFinished: false,
  },

  // Jupiler Pro League (ID: 5)
  {
    id: 'm17',
    color: 'success',
    title: 'Club Brugge vs Anderlecht',
    datef: new Date('2024-08-16'),
    league: '5',
    homeTeam: 'Club Brugge',
    awayTeam: 'Anderlecht',
    homeTeamLogo: 'https://crests.football-data.org/569.svg',
    awayTeamLogo: 'https://crests.football-data.org/570.svg',
    date: '2024-08-16T20:00:00Z',
    status: 'scheduled',
    isFinished: false,
  },
  {
    id: 'm18',
    color: 'success',
    title: 'Genk vs Gent',
    datef: new Date('2024-08-17'),
    league: '5',
    homeTeam: 'Genk',
    awayTeam: 'Gent',
    homeTeamLogo: 'https://crests.football-data.org/576.svg',
    awayTeamLogo: 'https://crests.football-data.org/577.svg',
    date: '2024-08-17T21:00:00Z',
    status: 'live',
    isFinished: false,
    homeScore: 0,
    awayScore: 0,
  },
  {
    id: 'm19',
    color: 'success',
    title: 'Standard Liège vs Antwerp',
    datef: new Date('2024-08-18'),
    league: '5',
    homeTeam: 'Standard Liège',
    awayTeam: 'Antwerp',
    homeTeamLogo: 'https://crests.football-data.org/575.svg',
    awayTeamLogo: 'https://crests.football-data.org/5691.svg',
    date: '2024-08-18T18:00:00Z',
    status: 'finished',
    isFinished: true,
    homeScore: 1,
    awayScore: 3,
  },
  {
    id: 'm20',
    color: 'success',
    title: 'Charleroi vs Eupen',
    datef: new Date('2024-08-19'),
    league: '5',
    homeTeam: 'Charleroi',
    awayTeam: 'Eupen',
    homeTeamLogo: 'https://crests.football-data.org/574.svg',
    awayTeamLogo: 'https://crests.football-data.org/573.svg',
    date: '2024-08-19T15:00:00Z',
    status: 'scheduled',
    isFinished: false,
  },
];
